extra:
  pagetime: 'on'
  search:
    language: cn
extra_css:
- from_oi_wiki/css/extra.css?v=13
extra_javascript:
- from_oi_wiki/js/extra.js?v=16
- js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- nl2br
- admonition
- pymdownx.details
- pymdownx.superfences
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify ''
- admonition
- abbr
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo: mkdocs-material
    repo_url_shorthand: true
    user: squidfunk
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- RABBIT:
  - ME: index.md
- About:
  - About: posts/About/index.md
- Conservative_Genetics:
  - Conservative_Genetics: posts/Conservative_Genetics/index.md
  - lecture1: posts/Conservative_Genetics/lecture1.md
plugins:
- search
repo_name: Qiaowuyan Pages
repo_url: https://github.com/qiaowuyan/qiaowuyan.github.io
site_name: Penguin Ice Land
site_url: https://qiaowuyan.github.io/
theme:
  custom_dir: overrides
  favicon: asset/DSC_3222.JPG
  features:
  - navigation.tabs
  font:
    code: Fira Mono
    text: Fira Sans
  language: en
  logo: asset/DSC_3222.JPG
  name: material
  palette:
    primary: black
    scheme: default
